export const data = [
    {
        id: 1,
        name: "Rokhim",
        productimage: "https://joeschmoe.io/api/v1/random",
        tanggal: "1/02/1997",
        tempat: "Malang",
        alamat: "London Kulas Ligh Apt. 556",
        instagram: "Rokhimuniverse",
        facebook: "Rokhiman",
        hp: 1 - 463 - 123 - 4447,
        pendidikan: "S1 Kesejahteraan Sosial",
    },
    {
        id: 2,
        name: "Rokhim",
        productimage: "https://joeschmoe.io/api/v1/random",
        tanggal: "1/02/1997",
        tempat: "Malang",
        alamat: "London Kulas Ligh Apt. 556",
        instagram: "Rokhimuniverse",
        facebook: "Rokhiman",
        hp: 1 - 463 - 123 - 4447,
        pendidikan: "S1 Kesejahteraan Sosial",
    },
    {
        id: 3,
        name: "Rokhim",
        productimage: "https://joeschmoe.io/api/v1/random",
        tanggal: "1/02/1997",
        tempat: "Malang",
        alamat: "London Kulas Ligh Apt. 556",
        instagram: "Rokhimuniverse",
        facebook: "Rokhiman",
        hp: 1 - 463 - 123 - 4447,
        pendidikan: "S1 Kesejahteraan Sosial",
    },
    {
        id: 4,
        name: "Rokhim",
        productimage: "https://joeschmoe.io/api/v1/random",
        tanggal: "1/02/1997",
        tempat: "Malang",
        alamat: "London Kulas Ligh Apt. 556",
        instagram: "Rokhimuniverse",
        facebook: "Rokhiman",
        hp: 1 - 463 - 123 - 4447,
        pendidikan: "S1 Kesejahteraan Sosial",
    },
    {
        id: 5,
        name: "Rokhim",
        productimage: "https://joeschmoe.io/api/v1/random",
        tanggal: "1/02/1997",
        tempat: "Malang",
        alamat: "London Kulas Ligh Apt. 556",
        instagram: "Rokhimuniverse",
        facebook: "Rokhiman",
        hp: 1 - 463 - 123 - 4447,
        pendidikan: "S1 Kesejahteraan Sosial",
    },
    {
        id: 6,
        name: "Rokhim",
        productimage: "https://joeschmoe.io/api/v1/random",
        tanggal: "1/02/1997",
        tempat: "Malang",
        alamat: "London Kulas Ligh Apt. 556",
        instagram: "Rokhimuniverse",
        facebook: "Rokhiman",
        hp: 1 - 463 - 123 - 4447,
        pendidikan: "S1 Kesejahteraan Sosial",
    },
    {
        id: 7,
        name: "Rokhim",
        productimage: "https://joeschmoe.io/api/v1/random",
        tanggal: "1/02/1997",
        tempat: "Malang",
        alamat: "London Kulas Ligh Apt. 556",
        instagram: "Rokhimuniverse",
        facebook: "Rokhiman",
        hp: 1 - 463 - 123 - 4447,
        pendidikan: "S1 Kesejahteraan Sosial",
    },
    {
        id: 8,
        name: "Rokhim",
        productimage: "https://joeschmoe.io/api/v1/random",
        tanggal: "1/02/1997",
        tempat: "Malang",
        alamat: "London Kulas Ligh Apt. 556",
        instagram: "Rokhimuniverse",
        facebook: "Rokhiman",
        hp: 1 - 463 - 123 - 4447,
        pendidikan: "S1 Kesejahteraan Sosial",
    },
    {
        id: 9,
        name: "Rokhim",
        productimage: "https://joeschmoe.io/api/v1/random",
        tanggal: "1/02/1997",
        tempat: "Malang",
        alamat: "London Kulas Ligh Apt. 556",
        instagram: "Rokhimuniverse",
        facebook: "Rokhiman",
        hp: 1 - 463 - 123 - 4447,
        pendidikan: "S1 Kesejahteraan Sosial",
    },
    {
        id: 10,
        name: "Rokhim",
        productimage: "https://joeschmoe.io/api/v1/random",
        tanggal: "1/02/1997",
        tempat: "Malang",
        alamat: "London Kulas Ligh Apt. 556",
        instagram: "Rokhimuniverse",
        facebook: "Rokhiman",
        hp: 1 - 463 - 123 - 4447,
        pendidikan: "S1 Kesejahteraan Sosial",
    },

];
